package com.liskovsoft.youtubeapi.app.potokennp2.core

import android.content.Context
import java.io.Closeable

/**
 * This interface was created to allow for multiple methods to generate poTokens in the future (e.g.
 * via WebView and via a local DOM implementation)
 */
internal interface PoTokenGenerator : Closeable {
    /**
     * Generates a poToken for the provided identifier, using the `integrityToken` and
     * `webPoSignalOutput` previously obtained in the initialization of [com.liskovsoft.youtubeapi.app.potokennp2.generators.PoTokenWebView]. Can be
     * called multiple times.
     */
    fun generatePoToken(identifier: String): String

    /**
     * @return whether the `integrityToken` is expired, in which case all tokens generated by
     * [generatePoToken] will be invalid
     */
    fun isExpired(): Boolean

    /**
     * NEWTUBE(pot-wv4): secret-free NetPath fields describing how this generator got its BotGuard
     * challenge (`challenge=`, `ytcfg=`, `eventId=`...), appended to the `web-pot-session` line.
     * Never a token, a visitor or a page value.
     */
    fun diagnostics(): String = ""

    interface Factory {
        /**
         * Initializes a [PoTokenGenerator] by loading the BotGuard VM, running it, and obtaining
         * an `integrityToken`. Can then be used multiple times to generate multiple poTokens with
         * [generatePoToken].
         *
         * @param context used e.g. to load the HTML asset or to instantiate a WebView
         */
        fun newPoTokenGenerator(context: Context): PoTokenGenerator
    }
}
